const base=String(process.env.BASE_URL||"http://127.0.0.1:8787").replace(/\/+$/,"");
function assert(c,m){if(!c)throw new Error(m);}
async function req(path,{method="POST",token="",body,expected=[200]}={}){const headers={accept:"application/json"};if(body!==undefined)headers["content-type"]="application/json";if(token)headers.authorization=`Bearer ${token}`;const r=await fetch(base+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body),redirect:"manual"});const text=await r.text();let data=null;try{data=text?JSON.parse(text):null;}catch{data={raw:text};}if(!expected.includes(r.status))throw new Error(`${path}: HTTP ${r.status}, expected ${expected.join("/")}; ${text.slice(0,600)}`);return{r,data};}
try{
 const status=await req("/api/status",{method:"GET"});assert(status.data?.ok===true,"status.ok");assert(status.data?.configured===true,"configured");assert(status.data?.cloudSave===true,"cloudSave");assert(status.data?.onlineRooms===true,"onlineRooms");assert(status.data?.storage==="cloudflare-d1","storage");
 const suffix=`${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`,password=`Teste!${suffix}Aa9`,a=`e2ea_${suffix}`.slice(0,32),b=`e2eb_${suffix}`.slice(0,32);
 const ra=await req("/api/auth/register",{body:{username:a,password,displayName:"E2E A"},expected:[201]}),rb=await req("/api/auth/register",{body:{username:b,password,displayName:"E2E B"},expected:[201]});assert(ra.data?.token&&rb.data?.token,"tokens");const ta=ra.data.token,tb=rb.data.token;
 const me=await req("/api/auth/me",{token:ta});assert(me.data?.account?.username===a,"me");const unauth=await req("/api/account/slots",{expected:[401]});assert(unauth.data?.error==="UNAUTHORIZED","unauth");
 const slot=`slot-${suffix}`,marker=`marker-${suffix}`,save={version:"R41-E2E",playerId:`p-${suffix}`,campaignId:`c-${suffix}`,character:{name:"Teste",level:7,pv:20,chakra:18},resources:{chakra:18,kurai:8},world:{marker}};
 const sw=await req("/api/account/save",{token:ta,body:{slotId:slot,save,gameVersion:"R41-E2E"}});assert(sw.data?.saved===true&&sw.data?.revision===1,"save");const ld=await req("/api/account/load",{token:ta,body:{slotId:slot}});assert(ld.data?.save?.world?.marker===marker,"load marker");assert(ld.data?.save?.resources?.kurai===8,"load kurai");
 const room=await req("/api/online/create",{token:ta,body:{title:`E2E ${suffix}`,campaignId:`c-${suffix}`,playerId:`pa-${suffix}`,character:{name:"A",level:7}}}),roomId=room.data?.roomId;assert(String(roomId).startsWith("room-"),"room id");
 await req("/api/online/join",{token:tb,body:{roomId,playerId:`pb-${suffix}`,character:{name:"B",level:5}}});await req("/api/online/heartbeat",{token:ta,body:{roomId,playerId:`pa-${suffix}`}});await req("/api/online/heartbeat",{token:tb,body:{roomId,playerId:`pb-${suffix}`}});
 const msg=`oi-${suffix}`;await req("/api/online/message",{token:ta,body:{roomId,playerId:`pa-${suffix}`,characterName:"A",message:msg}});const msgs=await req("/api/online/messages",{token:tb,body:{roomId,afterId:0}});assert(msgs.data?.messages?.some(x=>x.message===msg),"message sync");
 const intent=await req("/api/online/action",{token:ta,body:{roomId,playerId:`pa-${suffix}`,action:{type:"move",intent:"move",direction:"north",target:"training-field"}}});assert(intent.data?.accepted===true,"intent accepted");
 const forged=await req("/api/online/action",{token:ta,body:{roomId,playerId:`pa-${suffix}`,action:{type:"attack",intent:"attack",damage:999,success:true,xp:5000}},expected:[400]});assert(forged.data?.error==="CLIENT_MECHANICAL_RESULT_FORBIDDEN","forged mechanics rejected");
 const st=await req("/api/online/state",{token:tb,body:{roomId}});assert((st.data?.state?.members||[]).length>=2,"members sync");assert((st.data?.state?.actions||[]).some(x=>x.type==="move"),"action sync");
 const we=await req("/api/v84/world/event",{token:ta,body:{type:"world_tick",campaignId:`c-${suffix}`,minutes:20,source:"local-e2e",detail:{marker}}});assert(we.data?.ok===true,"world event");const sp=await req("/api/v84/world/savepoint",{token:ta,body:{campaignId:`c-${suffix}`,label:`E2E ${suffix}`,changes:["save"],character:{name:"Teste",level:7}}});assert(sp.data?.ok===true,"savepoint");
 await req("/api/account/delete",{token:ta,body:{slotId:slot}});await req("/api/auth/logout",{token:ta,body:{}});const gone=await req("/api/auth/me",{token:ta,expected:[401]});assert(gone.data?.error==="UNAUTHORIZED","logout");await req("/api/auth/logout",{token:tb,body:{}});
 console.log("PASS_LOCAL_D1_BACKEND_E2E");
}catch(e){console.error("FAIL_LOCAL_D1_BACKEND_E2E");console.error(e?.stack||e);process.exit(1);}
