import { DurableObject } from "cloudflare:workers";

const enc = new TextEncoder();
const JSON_HEADERS = { "content-type": "application/json; charset=utf-8" };
const BUILD = "R41-CLOUDFLARE-D1-INTEGRAL-20260820";
const TOKEN_MS = 30 * 24 * 60 * 60 * 1000;
let schemaReady = false;

function b64url(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function unb64url(s){s=String(s||"").replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";const raw=atob(s),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out;}
async function sha256Text(v){return b64url(new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(String(v)))));}
async function hashPassword(password,salt,iterations=210000){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return b64url(new Uint8Array(bits));}
function timingSafe(a,b){a=String(a||"");b=String(b||"");if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function randomBytes(n=16){const a=new Uint8Array(n);crypto.getRandomValues(a);return a;}
function randomSecret(n=32){return b64url(randomBytes(n));}
function norm(v){return String(v??"").trim();}
function cleanText(v,max=120){return norm(v).slice(0,max);}
function bearer(req){const h=req.headers.get("authorization")||"";return /^Bearer\s+/i.test(h)?h.replace(/^Bearer\s+/i,"").trim():"";}
function nowIso(){return new Date().toISOString();}
function roomId(){return `room-${crypto.randomUUID()}`;}
function safeJson(v,fallback=null){try{return JSON.parse(v);}catch{return fallback;}}
function safeAccount(u){return{id:String(u.id),username:u.username,displayName:u.display_name||u.username,role:u.role||"player",createdAt:u.created_at};}
function cors(req,env){const origin=req.headers.get("origin")||"",configured=String(env.ALLOWED_ORIGINS||"https://kaalflash12.github.io").split(",").map(x=>x.trim()).filter(Boolean),allowed=[...new Set([...configured,"http://localhost:8000","http://127.0.0.1:8000","http://localhost:8787","http://127.0.0.1:8787"])],selected=allowed.includes(origin)?origin:(!origin?allowed[0]:"null");return{"access-control-allow-origin":selected,"access-control-allow-methods":"GET,POST,PUT,PATCH,DELETE,OPTIONS","access-control-allow-headers":"authorization,content-type,x-r41-revision","access-control-expose-headers":"x-r41-revision","access-control-max-age":"86400","cache-control":"no-store","vary":"origin"};}
function reply(req,env,status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...cors(req,env),...extra}});}
async function bodyJson(req){try{return await req.json();}catch{return{};}}
function clampSaveForStorage(save){if(!save||typeof save!=="object"||Array.isArray(save))throw new Error("SAVE_INVALID");const raw=JSON.stringify(save);if(raw.length>1800000)throw new Error("SAVE_TOO_LARGE");return{value:save,raw};}
async function ensureSchema(env){if(schemaReady)return;if(!env.DB)throw new Error("D1_NOT_BOUND");const statements=[`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT NOT NULL,username_lower TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'player',pass_salt TEXT NOT NULL,pass_hash TEXT NOT NULL,pass_iter INTEGER NOT NULL DEFAULT 210000,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS sessions(sid TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,user_id TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,revoked_at TEXT)`,`CREATE TABLE IF NOT EXISTS saves(user_id TEXT NOT NULL,slot_id TEXT NOT NULL,data_json TEXT NOT NULL,player_id TEXT,campaign_id TEXT,game_version TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,PRIMARY KEY(user_id,slot_id))`,`CREATE TABLE IF NOT EXISTS friends(owner_id TEXT NOT NULL,friend_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(owner_id,friend_id))`,`CREATE TABLE IF NOT EXISTS room_registry(room_id TEXT PRIMARY KEY,title TEXT,campaign_id TEXT,owner_user_id TEXT NOT NULL,mode TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS world_events(id INTEGER PRIMARY KEY AUTOINCREMENT,campaign_id TEXT NOT NULL,type TEXT NOT NULL,detail_json TEXT NOT NULL DEFAULT '{}',minutes REAL NOT NULL DEFAULT 0,source TEXT NOT NULL,user_id TEXT NOT NULL,created_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS world_state(campaign_id TEXT PRIMARY KEY,last_savepoint_json TEXT,world_json TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,type TEXT NOT NULL,user_id TEXT,detail_json TEXT NOT NULL DEFAULT '{}',build TEXT NOT NULL,created_at TEXT NOT NULL)`,`CREATE TABLE IF NOT EXISTS recovery_codes(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,hash TEXT NOT NULL,salt TEXT NOT NULL,iterations INTEGER NOT NULL DEFAULT 120000,used INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,used_at TEXT)`,`CREATE INDEX IF NOT EXISTS ix_sessions_user ON sessions(user_id)`,`CREATE INDEX IF NOT EXISTS ix_sessions_exp ON sessions(expires_at)`,`CREATE INDEX IF NOT EXISTS ix_saves_player ON saves(player_id)`,`CREATE INDEX IF NOT EXISTS ix_saves_updated ON saves(updated_at)`,`CREATE INDEX IF NOT EXISTS ix_rooms_updated ON room_registry(updated_at)`,`CREATE INDEX IF NOT EXISTS ix_world_events_campaign ON world_events(campaign_id,created_at DESC)`,`CREATE INDEX IF NOT EXISTS ix_audit_events_time ON audit_events(created_at DESC)`,`CREATE INDEX IF NOT EXISTS ix_recovery_user ON recovery_codes(user_id)`];await env.DB.batch(statements.map(sql=>env.DB.prepare(sql)));schemaReady=true;}
async function audit(env,type,userId,detail={}){try{await env.DB.prepare("INSERT INTO audit_events(type,user_id,detail_json,build,created_at) VALUES(?,?,?,?,?)").bind(type,userId||null,JSON.stringify(detail),BUILD,nowIso()).run();}catch{}}
async function issueToken(env,user){const token=randomSecret(36),sid=crypto.randomUUID(),tokenHash=await sha256Text(token),createdAt=nowIso(),expiresAt=new Date(Date.now()+TOKEN_MS).toISOString();await env.DB.prepare("INSERT INTO sessions(sid,token_hash,user_id,created_at,expires_at,revoked) VALUES(?,?,?,?,?,0)").bind(sid,tokenHash,user.id,createdAt,expiresAt).run();return token;}
async function verifyToken(env,token){if(!token)return null;const tokenHash=await sha256Text(token);return env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.revoked=0 AND s.expires_at>? LIMIT 1").bind(tokenHash,nowIso()).first();}
async function requireUser(req,env){return verifyToken(env,bearer(req));}
async function revokeCurrent(req,env){const token=bearer(req);if(!token)return;await env.DB.prepare("UPDATE sessions SET revoked=1,revoked_at=? WHERE token_hash=?").bind(nowIso(),await sha256Text(token)).run();}
function slotSummary(row){const data=safeJson(row.data_json,{})||{},c=data.character||{};return{slotId:row.slot_id,name:c.name||c.nome||"Personagem",level:Number(c.level||c.nivel||1),graduation:c.graduation||c.graduacao||"",avatar:c.avatar||c.portrait||"",updatedAt:row.updated_at||null,gameVersion:row.game_version||""};}
function hasForbiddenMechanicalResult(v,depth=0){if(!v||typeof v!=="object"||depth>3)return false;const forbidden=new Set(["damage","dano","success","sucesso","xp","experience","level","nivel","roll","rolagem","result","resultado","critical","critico","healing","cura","reward","recompensa","hit","acerto","miss","falha","conditionApplied","conditionsApplied"]);for(const[k,x]of Object.entries(v)){if(forbidden.has(k))return true;if(x&&typeof x==="object"&&hasForbiddenMechanicalResult(x,depth+1))return true;}return false;}

export class GameRoom extends DurableObject{
 constructor(ctx,env){super(ctx,env);this.ctx=ctx;this.env=env;}
 async read(){return(await this.ctx.storage.get("room"))||null;}
 async write(room){room.updatedAt=nowIso();await this.ctx.storage.put("room",room);return room;}
 liveMembers(room){const cutoff=Date.now()-120000;return Object.values(room?.members||{}).filter(m=>Date.parse(m.lastSeen||0)>=cutoff);}
 async fetch(req){const u=new URL(req.url),action=u.pathname.replace(/^\/+/,"");let room=await this.read(),b={};if(req.method!=="GET")try{b=await req.json();}catch{}
  if(action==="create"){if(room)return Response.json({ok:false,error:"ROOM_ALREADY_EXISTS"},{status:409});room={roomId:b.roomId,title:cleanText(b.title||"Campanha Online",80),campaignId:cleanText(b.campaignId,100),mode:b.mode||"online",ownerUserId:b.userId,members:{},messages:[],actions:[],nextMessageId:1,createdAt:nowIso(),updatedAt:nowIso()};room.members[b.userId]={userId:b.userId,playerId:b.playerId,character:b.character||{},role:"host",joinedAt:nowIso(),lastSeen:nowIso()};await this.write(room);return Response.json({ok:true,roomId:room.roomId,title:room.title,campaignId:room.campaignId,room,members:this.liveMembers(room)});}
  if(!room)return Response.json({ok:false,error:"ROOM_NOT_FOUND"},{status:404});
  if(action==="join"){room.members[b.userId]={...(room.members[b.userId]||{}),userId:b.userId,playerId:b.playerId,character:b.character||{},role:room.ownerUserId===b.userId?"host":"member",joinedAt:room.members[b.userId]?.joinedAt||nowIso(),lastSeen:nowIso()};await this.write(room);return Response.json({ok:true,roomId:room.roomId,title:room.title,campaignId:room.campaignId,room,members:this.liveMembers(room)});}
  if(action==="heartbeat"){if(!room.members[b.userId])room.members[b.userId]={userId:b.userId,playerId:b.playerId,joinedAt:nowIso(),role:"member"};room.members[b.userId].lastSeen=nowIso();if(b.character)room.members[b.userId].character=b.character;await this.write(room);return Response.json({ok:true,serverTime:nowIso()});}
  if(action==="room")return Response.json({ok:true,room:{roomId:room.roomId,title:room.title,campaignId:room.campaignId,mode:room.mode,ownerUserId:room.ownerUserId,createdAt:room.createdAt,updatedAt:room.updatedAt},members:this.liveMembers(room)});
  if(action==="message"){const message=cleanText(b.message,1000);if(!message)return Response.json({ok:false,error:"MESSAGE_EMPTY"},{status:400});const m={id:room.nextMessageId++,userId:b.userId,playerId:b.playerId||"",characterName:cleanText(b.characterName||"Shinobi",80),message,createdAt:nowIso()};room.messages.push(m);room.messages=room.messages.slice(-250);await this.write(room);return Response.json({ok:true,message:m});}
  if(action==="messages"){const after=Number(u.searchParams.get("afterId")||b.afterId||0);return Response.json({ok:true,messages:room.messages.filter(x=>Number(x.id)>after).slice(-250)});}
  if(action==="action"){const envelope=b.action??b,type=cleanText(envelope?.type||envelope?.action||"action",80);if(/grant|award|give.?xp|set.?level|admin/i.test(type)||hasForbiddenMechanicalResult(envelope))return Response.json({ok:false,error:"CLIENT_MECHANICAL_RESULT_FORBIDDEN"},{status:400});const ev={id:crypto.randomUUID(),userId:b.userId,playerId:b.playerId||"",type,payload:envelope,createdAt:nowIso()};room.actions.push(ev);room.actions=room.actions.slice(-200);await this.write(room);return Response.json({ok:true,accepted:true,event:ev,serverTime:nowIso()});}
  if(action==="state")return Response.json({ok:true,state:{room:{roomId:room.roomId,title:room.title,campaignId:room.campaignId,mode:room.mode},members:this.liveMembers(room),messages:room.messages.slice(-100),actions:room.actions.slice(-100)}});
  return Response.json({ok:false,error:"ROOM_ROUTE_NOT_FOUND"},{status:404});
 }
}
async function roomJson(env,id,action,payload={},query=""){const stub=env.GAME_ROOMS.getByName(id),r=await stub.fetch(`https://room.internal/${action}${query}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),d=await r.json().catch(()=>({}));return{status:r.status,data:d};}
async function aiRoute(req,env){if(!env.AI)return reply(req,env,503,{ok:false,error:"WORKERS_AI_NOT_BOUND"});const b=await bodyJson(req),facts=b?.gameContext?.facts||b?.facts||[],rules=b?.gameContext?.rules||"TERION 2D10 resolve resultados mecânicos antes da narrativa.",system=`Você é o narrador do Shinobi no Sho. TERION é a autoridade mecânica. Nunca invente sucesso, dano, recompensa, técnica desbloqueada, morte ou relação que não esteja nos fatos confirmados. Narre consequência de fatos confirmados e ofereça ações possíveis. ${rules}`,prompt=JSON.stringify({mode:b.mode||"game_master",intent:b.intent||b.action||b.text||"continuar",facts,director:b.director||{},context:b.gameContext||b.context||{}}).slice(0,45000),result=await env.AI.run("@cf/meta/llama-3.2-1b-instruct",{messages:[{role:"system",content:system},{role:"user",content:prompt}]}),text=result?.response||result?.result?.response||result?.text||JSON.stringify(result);return reply(req,env,200,{ok:true,result:text,provider:"cloudflare-workers-ai",model:"@cf/meta/llama-3.2-1b-instruct",role:b.mode||"game_master"});}

async function handleApi(req,env){await ensureSchema(env);const url=new URL(req.url),path=url.pathname.replace(/\/+$/g,"")||"/";
 if(path==="/api/status")return reply(req,env,200,{ok:true,service:"naruto-shinobi-no-sho-online",build:BUILD,enabled:!!env.AI,provider:env.AI?"cloudflare-workers-ai":"offline",model:env.AI?"@cf/meta/llama-3.2-1b-instruct":null,envFound:!!env.AI,cloudSave:!!env.DB,memory:!!env.DB,rulesDatabase:true,onlineRooms:!!env.GAME_ROOMS,providers:[{id:"workers-ai",enabled:!!env.AI}],routes:{auth:true,save:true,online:true,pvp:true,coop:true,world:true,ai:!!env.AI},storage:"cloudflare-d1",realtime:"cloudflare-durable-objects",configured:!!(env.DB&&env.GAME_ROOMS)});
 try{
  if(path==="/api/auth/register"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),password=String(b.password||""),displayName=cleanText(b.displayName||username,60);if(!/^[\p{L}\p{N}_.-]{3,32}$/u.test(username)||password.length<8||password.length>200)return reply(req,env,400,{ok:false,error:"INVALID_CREDENTIALS_FORMAT"});const id=crypto.randomUUID(),salt=randomBytes(),passHash=await hashPassword(password,salt),now=nowIso();try{await env.DB.prepare("INSERT INTO users(id,username,username_lower,display_name,role,pass_salt,pass_hash,pass_iter,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,username,username.toLowerCase(),displayName,"player",b64url(salt),passHash,210000,now,now).run();}catch(e){if(/UNIQUE constraint failed/i.test(String(e?.message||e)))return reply(req,env,409,{ok:false,error:"USERNAME_EXISTS"});throw e;}const user={id,username,display_name:displayName,role:"player",created_at:now},token=await issueToken(env,user),recoveryCode=randomSecret(18),recoverySalt=randomBytes(),recoveryHash=await hashPassword(recoveryCode,recoverySalt,120000);await env.DB.prepare("INSERT INTO recovery_codes(id,user_id,hash,salt,iterations,used,created_at) VALUES(?,?,?,?,?,0,?)").bind(crypto.randomUUID(),id,recoveryHash,b64url(recoverySalt),120000,now).run();await audit(env,"auth.register",id,{username});return reply(req,env,201,{ok:true,token,account:safeAccount(user),recoveryCode,mirrors:{cloud:true,d1:true,drive:false}});}
  if(path==="/api/auth/login"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),password=String(b.password||""),u=await env.DB.prepare("SELECT * FROM users WHERE username_lower=? LIMIT 1").bind(username.toLowerCase()).first();if(!u)return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});const got=await hashPassword(password,unb64url(u.pass_salt),Number(u.pass_iter||210000));if(!timingSafe(got,u.pass_hash))return reply(req,env,401,{ok:false,error:"LOGIN_INVALID"});const token=await issueToken(env,u);await audit(env,"auth.login",u.id,{});return reply(req,env,200,{ok:true,token,account:safeAccount(u),mirrors:{cloud:true,d1:true,drive:false}});}
  if(path==="/api/auth/recover"&&req.method==="POST"){const b=await bodyJson(req),username=cleanText(b.username,32),code=String(b.recoveryCode||""),newPassword=String(b.newPassword||"");if(newPassword.length<8)return reply(req,env,400,{ok:false,error:"PASSWORD_TOO_SHORT"});const u=await env.DB.prepare("SELECT * FROM users WHERE username_lower=? LIMIT 1").bind(username.toLowerCase()).first();if(!u)return reply(req,env,401,{ok:false,error:"RECOVERY_INVALID"});const{results}=await env.DB.prepare("SELECT * FROM recovery_codes WHERE user_id=? AND used=0 ORDER BY created_at DESC LIMIT 10").bind(u.id).all();let match=null;for(const rc of results||[]){const got=await hashPassword(code,unb64url(rc.salt),Number(rc.iterations||120000));if(timingSafe(got,rc.hash)){match=rc;break;}}if(!match)return reply(req,env,401,{ok:false,error:"RECOVERY_INVALID"});const salt=randomBytes(),passHash=await hashPassword(newPassword,salt),now=nowIso();await env.DB.batch([env.DB.prepare("UPDATE users SET pass_salt=?,pass_hash=?,pass_iter=210000,updated_at=? WHERE id=?").bind(b64url(salt),passHash,now,u.id),env.DB.prepare("UPDATE recovery_codes SET used=1,used_at=? WHERE id=?").bind(now,match.id),env.DB.prepare("UPDATE sessions SET revoked=1,revoked_at=? WHERE user_id=?").bind(now,u.id)]);return reply(req,env,200,{ok:true,recovered:true});}
  if(path==="/api/ai"&&req.method==="POST")return aiRoute(req,env);
  if(path==="/api/v84/bootstrap"){const user=await requireUser(req,env),b=req.method==="POST"?await bodyJson(req):{},campaignId=user?cleanText(b.campaignId,120):"public";let world={npcs:[],arcs:[],missions:[],locations:[]};if(campaignId&&campaignId!=="public"){const ws=await env.DB.prepare("SELECT world_json FROM world_state WHERE campaign_id=? LIMIT 1").bind(campaignId).first();if(ws?.world_json)world=safeJson(ws.world_json,world);}return reply(req,env,200,{ok:true,world,serverTime:nowIso(),build:BUILD});}
  const user=await requireUser(req,env);
  if(path==="/api/auth/me")return user?reply(req,env,200,{ok:true,account:safeAccount(user),mirrors:{cloud:true,d1:true}}):reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
  if(!user)return reply(req,env,401,{ok:false,error:"UNAUTHORIZED"});
  if(path==="/api/auth/logout"){await revokeCurrent(req,env);return reply(req,env,200,{ok:true});}
  if(path==="/api/account/slots"){const{results}=await env.DB.prepare("SELECT * FROM saves WHERE user_id=? ORDER BY updated_at DESC").bind(user.id).all();return reply(req,env,200,{ok:true,slots:(results||[]).map(slotSummary),mirrors:{cloud:true,d1:true,drive:false}});}
  if(path==="/api/account/save"&&["POST","PUT"].includes(req.method)){const b=await bodyJson(req),slotId=cleanText(b.slotId||"slot-principal",100),{value:data,raw}=clampSaveForStorage(b.save??b.data),gameVersion=cleanText(b.gameVersion||data?.version||"R41",80),playerId=cleanText(data?.playerId,180)||null,campaignId=cleanText(data?.campaignId,180)||null,now=nowIso(),prior=await env.DB.prepare("SELECT revision,created_at FROM saves WHERE user_id=? AND slot_id=? LIMIT 1").bind(user.id,slotId).first(),revision=Number(prior?.revision||0)+1;await env.DB.prepare("INSERT INTO saves(user_id,slot_id,data_json,player_id,campaign_id,game_version,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,slot_id) DO UPDATE SET data_json=excluded.data_json,player_id=excluded.player_id,campaign_id=excluded.campaign_id,game_version=excluded.game_version,revision=excluded.revision,updated_at=excluded.updated_at").bind(user.id,slotId,raw,playerId,campaignId,gameVersion,revision,prior?.created_at||now,now).run();await audit(env,"save.write",user.id,{slotId,revision,gameVersion});return reply(req,env,200,{ok:true,saved:true,slotId,revision,updatedAt:now,mirrors:{cloud:true,d1:true,drive:false}},{"x-r41-revision":String(revision)});}
  if(path==="/api/account/load"){const b=await bodyJson(req),slotId=cleanText(b.slotId||"slot-principal",100),s=await env.DB.prepare("SELECT * FROM saves WHERE user_id=? AND slot_id=? LIMIT 1").bind(user.id,slotId).first();if(!s)return reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND",slotId});return reply(req,env,200,{ok:true,save:safeJson(s.data_json,{}),slotId:s.slot_id,revision:Number(s.revision||0),updatedAt:s.updated_at,mirrors:{cloud:true,d1:true,drive:false}},{"x-r41-revision":String(s.revision||0)});}
  if(path==="/api/account/delete"){const b=await bodyJson(req),slotId=cleanText(b.slotId,100);if(!slotId)return reply(req,env,400,{ok:false,error:"SLOT_REQUIRED"});const r=await env.DB.prepare("DELETE FROM saves WHERE user_id=? AND slot_id=?").bind(user.id,slotId).run();return reply(req,env,200,{ok:true,deleted:Number(r.meta?.changes||0)===1,slotId});}
  if(path==="/api/cloud/load"){const b=await bodyJson(req),playerId=cleanText(b.playerId,180),s=playerId?await env.DB.prepare("SELECT * FROM saves WHERE user_id=? AND player_id=? ORDER BY updated_at DESC LIMIT 1").bind(user.id,playerId).first():await env.DB.prepare("SELECT * FROM saves WHERE user_id=? ORDER BY updated_at DESC LIMIT 1").bind(user.id).first();if(!s)return reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND"});const data=safeJson(s.data_json,{});return reply(req,env,200,{ok:true,save:data,playerId:data?.playerId||playerId,campaignId:data?.campaignId||"",updatedAt:s.updated_at});}
  if(path==="/api/private/unlock"){if(user.role!=="leon")return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});return reply(req,env,200,{ok:true,session:bearer(req)||"account-session"});}
  if(path==="/api/private/leon/load"){if(user.role!=="leon")return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});const s=await env.DB.prepare("SELECT * FROM saves WHERE user_id=? AND slot_id='leon-private' LIMIT 1").bind(user.id).first();return s?reply(req,env,200,{ok:true,save:safeJson(s.data_json,{}),updatedAt:s.updated_at}):reply(req,env,404,{ok:false,error:"SAVE_NOT_FOUND"});}
  if(path==="/api/private/leon/save"){if(user.role!=="leon")return reply(req,env,403,{ok:false,error:"PRIVATE_ACCESS_DENIED"});const b=await bodyJson(req),{value:data,raw}=clampSaveForStorage(b.save),now=nowIso(),prior=await env.DB.prepare("SELECT revision,created_at FROM saves WHERE user_id=? AND slot_id='leon-private' LIMIT 1").bind(user.id).first(),revision=Number(prior?.revision||0)+1,gameVersion=cleanText(b.gameVersion||data?.version||"R41",80);await env.DB.prepare("INSERT INTO saves(user_id,slot_id,data_json,player_id,campaign_id,game_version,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(user_id,slot_id) DO UPDATE SET data_json=excluded.data_json,game_version=excluded.game_version,revision=excluded.revision,updated_at=excluded.updated_at").bind(user.id,"leon-private",raw,cleanText(data?.playerId,180)||null,cleanText(data?.campaignId,180)||null,gameVersion,revision,prior?.created_at||now,now).run();return reply(req,env,200,{ok:true,updatedAt:now,revision,mirrors:{cloud:true,d1:true,drive:false}});}
  if(path==="/api/leaderboard"){const{results}=await env.DB.prepare("SELECT s.data_json,u.username,u.display_name FROM saves s JOIN users u ON u.id=s.user_id ORDER BY s.updated_at DESC LIMIT 300").all(),rows=(results||[]).map(r=>{const d=safeJson(r.data_json,{})||{};return{username:r.username||"shinobi",displayName:r.display_name||r.username||"Shinobi",name:d.character?.name||null,level:Number(d.character?.level||1),xp:Number(d.stats?.totalXp||0),avatar:d.character?.avatar||""};}).sort((a,b)=>b.level-a.level||b.xp-a.xp).slice(0,50);return reply(req,env,200,{ok:true,leaderboard:rows});}
  if(path==="/api/friends"){const{results}=await env.DB.prepare("SELECT u.* FROM friends f JOIN users u ON u.id=f.friend_id WHERE f.owner_id=? ORDER BY f.created_at DESC").bind(user.id).all();return reply(req,env,200,{ok:true,friends:(results||[]).map(safeAccount)});}
  if(path==="/api/friends/add"){const b=await bodyJson(req),target=await env.DB.prepare("SELECT * FROM users WHERE username_lower=? LIMIT 1").bind(cleanText(b.username,32).toLowerCase()).first();if(!target)return reply(req,env,404,{ok:false,error:"USER_NOT_FOUND"});if(target.id===user.id)return reply(req,env,400,{ok:false,error:"SELF_FRIEND"});await env.DB.prepare("INSERT OR IGNORE INTO friends(owner_id,friend_id,created_at) VALUES(?,?,?)").bind(user.id,target.id,nowIso()).run();return reply(req,env,200,{ok:true,friend:safeAccount(target)});}
  if(path==="/api/online/create"){const b=await bodyJson(req),id=roomId(),r=await roomJson(env,id,"create",{...b,roomId:id,userId:user.id,mode:"online"});if(r.status<300){const now=nowIso();await env.DB.prepare("INSERT INTO room_registry(room_id,title,campaign_id,owner_user_id,mode,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(room_id) DO UPDATE SET title=excluded.title,campaign_id=excluded.campaign_id,updated_at=excluded.updated_at").bind(id,r.data.title||cleanText(b.title,80),r.data.campaignId||cleanText(b.campaignId,100),user.id,"online",now,now).run();}return reply(req,env,r.status,r.data);}
  if(path==="/api/online/join"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"join",{...b,userId:user.id});if(r.status<300)await env.DB.prepare("UPDATE room_registry SET updated_at=? WHERE room_id=?").bind(nowIso(),id).run();return reply(req,env,r.status,r.data);}
  if(path==="/api/online/heartbeat"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"heartbeat",{...b,userId:user.id});return reply(req,env,r.status,r.data);}
  if(path==="/api/online/room"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"room",{userId:user.id});return reply(req,env,r.status,r.data);}
  if(path==="/api/online/message"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"message",{...b,userId:user.id});return reply(req,env,r.status,r.data);}
  if(path==="/api/online/messages"){const b=await bodyJson(req),id=cleanText(b.roomId,120),afterId=Number(b.afterId||0);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const r=await roomJson(env,id,"messages",{userId:user.id,afterId},`?afterId=${encodeURIComponent(afterId)}`);return reply(req,env,r.status,r.data);}
  if(path==="/api/online/action"){const b=await bodyJson(req),id=cleanText(b.roomId||b.room?.roomId,120);if(id){const r=await roomJson(env,id,"action",{...b,userId:user.id});return reply(req,env,r.status,r.data);}if(hasForbiddenMechanicalResult(b))return reply(req,env,400,{ok:false,error:"CLIENT_MECHANICAL_RESULT_FORBIDDEN"});await audit(env,"online.action.unroomed",user.id,b);return reply(req,env,200,{ok:true,accepted:true,serverTime:nowIso()});}
  if(path==="/api/online/state"){const b=await bodyJson(req),id=cleanText(b.roomId,120);if(!id){const{results}=await env.DB.prepare("SELECT * FROM room_registry ORDER BY updated_at DESC LIMIT 20").all();return reply(req,env,200,{ok:true,state:{rooms:results||[]}});}const r=await roomJson(env,id,"state",{userId:user.id});return reply(req,env,r.status,r.data);}
  if(/^\/api\/(pvp|coop)\//.test(path)){const m=path.match(/^\/api\/(pvp|coop)\/([^/]+)$/),mode=m?.[1],action=m?.[2],b=await bodyJson(req);if(!mode)return reply(req,env,404,{ok:false,error:"ROUTE_NOT_FOUND"});if(action==="create"){const id=roomId(),r=await roomJson(env,id,"create",{...b,roomId:id,userId:user.id,mode});return reply(req,env,r.status,r.data);}const id=cleanText(b.roomId,120);if(!id)return reply(req,env,400,{ok:false,error:"ROOM_ID_REQUIRED"});const mapped=action==="join"?"join":action==="state"?"state":action==="action"?"action":action,r=await roomJson(env,id,mapped,{...b,userId:user.id});return reply(req,env,r.status,r.data);}
  if(path==="/api/v84/world/event"){const b=await bodyJson(req),campaignId=cleanText(b.campaignId||b.detail?.campaignId||"default",120),event={type:cleanText(b.type||"event",120),detail:b.detail||{},minutes:Number(b.minutes||0),source:cleanText(b.source||"r41",120),userId:user.id,campaignId,createdAt:nowIso()},r=await env.DB.prepare("INSERT INTO world_events(campaign_id,type,detail_json,minutes,source,user_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(event.campaignId,event.type,JSON.stringify(event.detail),event.minutes,event.source,event.userId,event.createdAt).run();return reply(req,env,200,{ok:true,event:{...event,id:r.meta?.last_row_id||null,at:event.createdAt}});}
  if(path==="/api/v84/world/savepoint"){const b=await bodyJson(req),campaignId=cleanText(b.campaignId||"default",120),now=nowIso(),savePoint={label:cleanText(b.label,180),changes:Array.isArray(b.changes)?b.changes.slice(-100):[],character:b.character||null,at:now},prior=await env.DB.prepare("SELECT created_at FROM world_state WHERE campaign_id=? LIMIT 1").bind(campaignId).first();await env.DB.prepare("INSERT INTO world_state(campaign_id,last_savepoint_json,world_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(campaign_id) DO UPDATE SET last_savepoint_json=excluded.last_savepoint_json,updated_at=excluded.updated_at").bind(campaignId,JSON.stringify(savePoint),null,prior?.created_at||now,now).run();return reply(req,env,200,{ok:true,savePoint:{label:savePoint.label,at:now}});}
  return reply(req,env,404,{ok:false,error:"ROUTE_NOT_FOUND",path});
 }catch(e){console.error("R41_D1_API_ERROR",e);const msg=String(e?.message||e);return reply(req,env,msg==="SAVE_TOO_LARGE"?413:500,{ok:false,error:msg.startsWith("SAVE_")?msg:"INTERNAL_ERROR"});}
}

export default{async fetch(req,env){if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(req,env)});const url=new URL(req.url),path=url.pathname.replace(/\/+$/g,"")||"/";if(path==="/"){const target=new URL(String(env.PUBLIC_GAME_URL||"https://kaalflash12.github.io/naruto-shinobi-no-sho/"));target.searchParams.set("api",url.origin);return Response.redirect(target.toString(),302);}if(path.startsWith("/api/"))return handleApi(req,env);if(path==="/health")return Response.json({ok:true,build:BUILD,storage:"cloudflare-d1"});return Response.json({ok:false,error:"NOT_FOUND",path},{status:404});}};
