name: Force Publish Request Scoped MongoDB Once Trigger
on:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - run: echo trigger
